name: Maven-Cucumber-Selenium-Test  # Use a valid name without special characters

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' 

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
          java-version: '11'
          distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Run Cucumber Tests
      run: mvn test
